from __future__ import annotations

from .contracts import DonorRole, MechanismSpec


DONORS: tuple[MechanismSpec, ...] = (
    MechanismSpec("duck_endogenous_planning", "Azimn/DUCK", "Endogenous goal formation and outcome-driven replanning", DonorRole.MECHANISM, "Lived experience can create a persistent goal, select a state-sensitive route, survive interruption, and replan after failure without an LLM owning executive state.", ("predicts", "decides", "acts", "learns"), 3.0),
    MechanismSpec("jelly_private_cognition_feedback", "Azimn/Jelly-Psiduck", "Private thought to grounded experience feedback", DonorRole.MECHANISM, "Admitted private cognition can alter later memory, appraisal, attention, or conduct without becoming objective world truth.", ("attends", "remembers", "learns", "decides"), 2.5),
    MechanismSpec("tiny_persona_perception", "Azimn/TinyPersonaEngine", "Character-relative perception and bounded attention", DonorRole.MECHANISM, "Spatial, modal, occlusion, and attention limits change what the subject can attend to and later remember while world truth remains host-owned.", ("attends", "remembers"), 2.0),
    MechanismSpec("pretorius_v6_recall_social", "Azimn/Pretorius", "Actor-indexed recall, dissonance, withholding, and self-ledger controls", DonorRole.MECHANISM, "Socially indexed autobiographical context should change recall and disclosure decisions for the same present interaction.", ("remembers", "decides", "acts"), 3.0),
    MechanismSpec("doctor_lives_state_policy_bridge", "Azimn/The-Doctor-Lives", "Causally audited state-to-policy bridge", DonorRole.MECHANISM, "Previously contextual but inert state should change action selection only when a measured bridge proves downstream causal effect.", ("decides", "acts"), 2.0),
    MechanismSpec("wayfarer_renderer_swap_benchmark", "Azimn/persona_engine_PYTHONX", "Renderer substitution benchmark", DonorRole.EVALUATION, "Renderer changes should alter wording more than semantic trajectory for a frozen developed subject.", ("decides", "acts"), 0.5),
    MechanismSpec("kiki_subjective_frame_receipt", "Azimn/Kiki-Mind", "Reproducible retrieval and subjective-frame receipt", DonorRole.PROVENANCE, "The exact evidence surface shown to a renderer should be attributable without granting retrieval canonical authority.", ("attends", "remembers"), 0.75),
    MechanismSpec("npc_activation_steering", "Azimn/npc-steering-plus", "Activation-space affect steering", DonorRole.MECHANISM, "Symbolic affect should track rendered affect more faithfully than prompt/card control alone while leaving canonical state upstream.", ("acts",), 3.0, True),
    MechanismSpec("digital_subject_continuity_influence", "Azimn/Persona-and-Jelly-Sandwich-", "Expectation and commitment continuity influence", DonorRole.MECHANISM, "Different lived expectation and commitment histories should bias the same present decision through bounded existing pressure channels.", ("predicts", "decides", "acts"), 1.5),
    MechanismSpec("first_person_involuntary_expression", "Azimn/FirstPersonLoopTest", "Involuntary versus intentional expression boundary", DonorRole.MECHANISM, "High-intensity internal events may trigger involuntary expression without exposing raw simulation state or converting it into deliberate speech.", ("attends", "acts"), 1.0),
    MechanismSpec("omnicore_six_dimensional_affect", "Azimn/Omnicore", "Six-dimensional affect candidate", DonorRole.HISTORICAL, "Agency, fidelity, novelty, dominance, valence, and arousal may add predictive value beyond Frankenstein's compact affect model.", ("predicts", "decides", "acts"), 2.0),
    MechanismSpec("recurrent_plastic_policy", "Azimn/Pretorius-Neural-Network + Gelatinblob sidecar", "Recurrent plastic policy substrate", DonorRole.MECHANISM, "History-sensitive tendencies not reducible to explicit scalar rules may improve longitudinal adaptation under matched histories.", ("learns", "decides", "acts"), 4.0),
    MechanismSpec("madman_resource_metabolism", "Azimn/metaphysical-man", "Resource-constrained emergent cognition", DonorRole.HISTORICAL, "Resource-flow dynamics may yield useful path dependence without hand-authored memory or attention abstractions.", ("attends", "learns", "decides"), 4.0),
    MechanismSpec("bicentennial_matched_history_protocol", "Azimn/Bicentennial-Man", "Matched-history and held-out transfer protocol", DonorRole.EVALUATION, "Candidate mechanisms must survive fixed-founder and matched-history controls rather than builder-selected anecdotes.", ("learns", "decides", "acts"), 0.5),
    MechanismSpec("kurzweil_developmental_counterfactuals", "Azimn/Kurzweil-Brain-Experiments", "Paired developmental counterfactual protocol", DonorRole.EVALUATION, "Different developmental environments should create measurable adult policy differences without answer-key leakage.", ("learns", "decides", "acts"), 0.5),
    MechanismSpec("champion_challenger_governance", "Azimn/champion-versus-challenger + Azimn/integration-harness", "Reuse-first mechanism qualification governance", DonorRole.PROVENANCE, "No new organ enters the trunk without a gap finding, donor provenance, ablation, and measurable longitudinal gain.", (), 0.25),
)


DONOR_BY_ID = {item.mechanism_id: item for item in DONORS}
