from __future__ import annotations

from .contracts import DonorRole, MechanismSpec

DONORS: tuple[MechanismSpec, ...] = (
    MechanismSpec("duck_endogenous_planning", "Azimn/DUCK", "Endogenous goal formation and outcome-driven replanning", DonorRole.MECHANISM, "Lived experience can create a persistent goal, select a state-sensitive route, survive interruption, and replan after failure without an LLM owning executive state.", ("predicts", "decides", "acts", "learns"), 0.22),
    MechanismSpec("jelly_private_cognition_feedback", "Azimn/Jelly-Psiduck", "Private thought to grounded experience feedback", DonorRole.MECHANISM, "Admitted private cognition can alter later memory, appraisal, attention, or conduct without becoming objective world truth.", ("attends", "remembers", "learns", "decides"), 0.30),
    MechanismSpec("tiny_persona_perception", "Azimn/TinyPersonaEngine", "Character-relative perception and bounded attention", DonorRole.DEPLOYMENT, "Spatial, modal, occlusion, and attention limits change what the subject can attend to and later remember while world truth remains host-owned.", ("attends", "remembers"), 0.18),
    MechanismSpec("pretorius_v6_recall_social", "Azimn/Pretorius", "Actor-indexed recall, epistemic provenance, dissonance, and withholding", DonorRole.MECHANISM, "Socially indexed autobiographical context and evidence class should improve recall of lived actor-specific evidence without promoting reconstruction to history.", ("remembers", "decides", "acts"), 0.27),
    MechanismSpec("doctor_lives_commitment_policy_bridge", "Azimn/The-Doctor-Lives", "Causally audited commitment-to-policy bridge", DonorRole.MECHANISM, "Durable commitment state that is present but inert should alter action selection only when a measured bridge proves downstream causal effect.", ("decides", "acts"), 0.20),
    MechanismSpec("wayfarer_renderer_swap_benchmark", "Azimn/persona_engine_PYTHONX", "Renderer substitution benchmark", DonorRole.EVALUATION, "Renderer changes should alter wording more than semantic trajectory for a frozen developed subject.", ("decides", "acts"), 0.05),
    MechanismSpec("kiki_subjective_frame_receipt", "Azimn/Kiki-Mind", "Reproducible retrieval and subjective-frame receipt", DonorRole.PROVENANCE, "The exact evidence surface shown to a renderer should be attributable without granting retrieval canonical authority.", ("attends", "remembers"), 0.08),
    MechanismSpec("npc_activation_steering", "Azimn/npc-steering-plus", "Activation-space affect steering", DonorRole.MECHANISM, "Symbolic affect should track rendered affect more faithfully than prompt/card control alone while leaving canonical state upstream.", ("acts",), 0.34, True),
    MechanismSpec("digital_subject_continuity_influence", "Azimn/Persona-and-Jelly-Sandwich-", "Expectation and commitment continuity influence", DonorRole.MECHANISM, "Different lived expectation and commitment histories should improve the same present decision beyond existing Frankenstein relationship pressure.", ("predicts", "decides", "acts"), 0.12),
    MechanismSpec("bounded_offscreen_catchup", "Azimn/Persona-and-Jelly-Sandwich- + Azimn/rho + Anima", "Bounded offscreen wall-clock catch-up", DonorRole.DEPLOYMENT, "Authoritative host time should produce bounded catch-up ticks with deferred remainder while leaving world and subject authority intact.", ("learns", "decides", "acts"), 0.12),
    MechanismSpec("first_person_involuntary_expression", "Azimn/FirstPersonLoopTest", "Involuntary versus intentional expression boundary", DonorRole.MECHANISM, "High-intensity internal events may trigger involuntary expression without exposing raw simulation state or converting it into deliberate speech.", ("attends", "acts"), 0.15),
    MechanismSpec("omnicore_six_dimensional_affect", "Azimn/Omnicore", "Six-dimensional affect candidate", DonorRole.HISTORICAL, "Agency, fidelity, novelty, dominance, valence, and arousal may add predictive value beyond Frankenstein's compact affect model.", ("predicts", "decides", "acts"), 0.28),
    MechanismSpec("recurrent_plastic_policy", "Azimn/Pretorius-Neural-Network + Gelatinblob sidecar", "Recurrent plastic policy substrate", DonorRole.MECHANISM, "History-sensitive tendencies not reducible to explicit scalar rules may improve longitudinal adaptation under matched histories.", ("learns", "decides", "acts"), 0.42),
    MechanismSpec("madman_resource_metabolism", "Azimn/metaphysical-man", "Resource-constrained emergent cognition", DonorRole.HISTORICAL, "Resource-flow dynamics may yield useful path dependence without hand-authored memory or attention abstractions.", ("attends", "learns", "decides"), 0.50),
    MechanismSpec("bicentennial_matched_history_protocol", "Azimn/Bicentennial-Man", "Matched-history and held-out transfer protocol", DonorRole.EVALUATION, "Candidate mechanisms must survive fixed-founder and matched-history controls rather than builder-selected anecdotes.", ("learns", "decides", "acts"), 0.05),
    MechanismSpec("kurzweil_developmental_counterfactuals", "Azimn/Kurzweil-Brain-Experiments", "Paired developmental counterfactual protocol", DonorRole.EVALUATION, "Different developmental environments should create measurable adult policy differences without answer-key leakage.", ("learns", "decides", "acts"), 0.5),
    MechanismSpec("champion_challenger_governance", "Azimn/champion-versus-challenger + Azimn/integration-harness", "Reuse-first mechanism qualification governance", DonorRole.PROVENANCE, "No new organ enters the trunk without a gap finding, donor provenance, ablation, and measurable longitudinal gain.", (), 0.05),
    MechanismSpec("personaforge_selective_dual_process", "fQwQf/PersonaForge", "Selective inner-monologue trigger", DonorRole.MECHANISM, "Triggering private deliberation only on high-value turns may preserve long-dialogue character quality at lower inference cost than always-on inner monologue.", ("decides", "acts"), 0.25, True),
    MechanismSpec("memora_forgetting_aware_memory_eval", "geniesinc/Memora", "Forgetting-aware long-horizon memory benchmark", DonorRole.EVALUATION, "Memory quality must reward both appropriate recall and appropriate absence after update or forgetting.", ("remembers",), 0.05),
    MechanismSpec("contextecho_long_session_drift_eval", "Accenture/ContextEcho", "Forked long-session persona-drift protocol", DonorRole.EVALUATION, "A frozen running subject should remain behaviorally recognizable under delayed probes without perturbing its main trajectory.", ("decides", "acts"), 0.05),
)

DONOR_BY_ID = {item.mechanism_id: item for item in DONORS}
